### ISSUE TITLE
Mudando emblema do eden

### ISSUE THREAD

**Issue by gabx257** [Nipodemos/up1-99_completo_para_arrauceiros#10]
Como você pediu no fórum cá estou :P
eu "fiz"(copiei das que já tinha) a macro para mudar o emblema bem simples pra você ver.alem de eu não saber meche no github

`automacro TrocarEmblema {`
	`InInventoryID = 6219`
	`exclusive 1`
	`call {`
		`do move moc_para01 &rand(33,35) &rand(25,27) #posição otima no Eden`
		`do talk $.NpcNearLastBinId`
		`do talk resp 0`
		`do iconf 22508 0 0 0 #Novo Emblema do Grupo Valhalla`
		`do conf -f membroDoEden sim`
	`}`
`}`

**Comment by Nipodemos** [comment]
cara, muito obrigado mesmo!!! eu estava animando ainda a fazer isso, porque eu teria que pegar a sequencia de conversação, mas tava com preguiça, e vc fez 😄 
valeu

**Comment by Nipodemos** [comment]
resolvido no último commit

se quiser manda um pull request da próxima
