### ISSUE TITLE
[WIP] Desativar esse repositorio para manter o foco em apenas 1

### ISSUE THREAD

**Issue by vitorsilverio** [Nipodemos/up1-99_completo_para_arrauceiros#27]
Para a parte de arruaceiro o repositório https://github.com/eventMacrosBR/up_1_ao_99_todas_classes-bro falta apenas a parte da poção laranja agora. Todas as outras funções já estão implementadas com o novo layout de organização de código. Assim que a poção laranja ser implementada esse repositório pode ser descontinuado

**Comment by Nipodemos** [comment]
concordo, vou esperar só essa parte mesmo e descontinuarei

**Comment by vitorsilverio** [comment]
Pots laranjas ok

**Comment by vitorsilverio** [comment]
Aguardando #28 para fechar este issue
