### ISSUE TITLE
[Sugestão] Refatoração Stats/Skills

### ISSUE THREAD

**Issue by vitorsilverio** [Nipodemos/up1-99_completo_para_arrauceiros#9]
Nipodemos,

Gostaria de sugerir a refatoração do trecho que seleciona o add skill e add stats, pois como comentei anteriormente gostaria de fazer a macro upar Aprendiz T. até Desordeiros. Isso vai evitar a reconfiguração de gastar skills para trocar classes. Essas configurações atualmente são feitas apenas se script pegar desde o campo de treinamento. Talvez um script 0parametrizacao.event para deixar usuários do script modificar isso logo no inicio do eventMacros.txt

Inicialmente seria separar essa parte:
```
do conf statsAddAuto 1
do conf statsAddAuto_list 10 dex, 15 agi, 20 dex, 25 agi, 20 str, 30 dex, 60 agi, 30 str, 40 dex, 20 vit, 80 agi, 25 luk ,60 dex, 50 str, 40 luk, 90 agi, 60 str, 29 vit
do conf statsAddAuto_dontUseBonus 1
do conf skillsAddAuto 1
do conf skillsAddAuto_list NV_BASIC 9, TF_DOUBLE 10, TF_MISS 10, TF_STEAL 10, TF_HIDING 8, TF_POISON 10, TF_DETOXIFY 1, RG_SNATCHER 10, RG_STEALCOIN 10, RG_BACKSTAP 4, RG_TUNNELDRIVE 5, RG_RAID 5, RG_INTIMIDATE 5, RG_PLAGIARISM 10
```

Se tiver tudo ok para você pode começar a fazer esse código

**Comment by Nipodemos** [comment]
cara nunca tinha pensado nisso... um arquivo de parametrização... é uma ideia genial!
inclusive é uma boa pra uma futura macro pra upar todas as classes

então poderia fazer parametrizações baseado na classe dele
* **Aprendiz**: NV_BASIC 9 e atributos padrão
* **Gatuno**: o resto das skills (só de gatuno)
* **Arrauceiro**: skills dele
* **Aprendiz T**: o mesmo NV_BASIC 9 mas distribuição de atributos de transclassee
* **Gatuno T**: o mesmo de gatuno, mas seguindo atributos de transclasse
* **Desordeiro**, skills dele

e também pensei, em criar uma configKey no config.txt com a classe atual do char
e sempre que ela mudar, o automacro de parametrização vai mudar tambem, e será reativado sempre que algo mudar

Essa ConfigKey pode ser definida na macro definindoVariáveisDeUp 
(que vai fazer com que a classe atual do bot seja cheecada a cada 5 minutos)

**Comment by vitorsilverio** [comment]
Eu falei sobre isso numa PM no forum, mas acho que não chegou a ver

**Comment by Nipodemos** [comment]
kkkk vi assim que terminei de escrever isso tudo ashuasuhash
mas saca só, tenho uma notícia boa pra vc:

https://github.com/Nipodemos/eventMacros/blob/master/upTodasAsClasses(incompleta).event
https://github.com/Nipodemos/eventMacros/blob/master/upTransclasses(incompleta).event
eu ja comecei o projeto, mas ta incompleto, o que significa que ja ta um pouco mais fácil
no final desse repositorio, tem a macro (upTodasasClasses)incompleta
e upTransclasse(incompleta) tambem

dá uma olhada lá que a gente ja consegue ter uma boa base, sem ter que reescrever toda a macro de arrauceiro :D

**Comment by Nipodemos** [comment]
a parte das quest de classe 2 é que vai ser a maior treta de todas

mas pelo menos ja temos a de arrauceiro, e eu e um amigo meu fizemos a de alquimista heheh
e alguem no fórum fez a de sacerdote no defasado macro plugin

**Comment by vitorsilverio** [comment]
A de Sacer eu testei e funcionou, eu dei bobeira sem querer e minha AB foi banida, mas agora só uso o openkore numa maquina linux a parte

**Comment by vitorsilverio** [comment]
O script https://github.com/Nipodemos/eventMacros/blob/master/upTodasAsClasses(incompleta).event podia ter um repositorio só para ele com todas as divisões ou trazido para este para acertarmos

**Comment by Nipodemos** [comment]
> O script https://github.com/Nipodemos/eventMacros/blob/master/upTodasAsClasses(incompleta).event podia ter um repositorio só para ele com todas as divisões ou trazido para este para acertarmos

como era só um projetinho que eu nao tinha dado atenção, nem pensei nisso, talvez fosse uma boa ideia mesmo. O ideal é fazer um novo repositório

> A de Sacer eu testei e funcionou, eu dei bobeira sem querer e minha AB foi banida, mas agora só uso o openkore numa maquina linux a parte

tem isso né... testar a macro criada.. tive muitos problemas com a quest alquimista, que parecia fácil, mas nao foi


bom... vou trabalhar agora, a gente troca ideia mais depois 👍

**Comment by Nipodemos** [comment]
Vc tá pensando em escrever essa refatoração? Ou é pra ver se eu posso fazer?

**Comment by vitorsilverio** [comment]
Ainda não comecei, estava estudando um pouco do openkore. Mas assim que tiver algo já iniciado e testado para pelo menos skills e stats eu abro um PR.

**Comment by vitorsilverio** [comment]
@Nipodemos  antes de submeter um pull request gostaria que desse uma olhada em https://github.com/vitorsilverio/up1-99_completo_para_arrauceiros/blob/parametrizacao/0parametrizacao.event e me desse alguma opinião

Sorry eu dou muito trabalho, mas ainda sou meio noob nesses macros

**Comment by vitorsilverio** [comment]
@Nipodemos criei uma organização e te adicionei, já tem o repositório em branco
https://github.com/eventMacrosBR/up_1_ao_99_todas_classes-bro

**Comment by Nipodemos** [comment]
vou fechar esse issue, ja que foi movido pra outra organização
